/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewEvents;
import java.beans.Statement;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Shavindya
 */
public class NewEvents extends javax.swing.JFrame {
     
    String EventName;
    String Description;
    String ContactNumber;
    String EventTime;
    String Keyword;
    
    public NewEvents() {
        initComponents();
        show_event();
    }
         public ArrayList<Event> eventList(){
             ArrayList<Event> eventsList = new ArrayList<>();
             try{
               Class.forName("com.mysql.jdbc.Driver");
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","password");
                 String sql = "Select * from handling";
                 java.sql.Statement st = con.createStatement();
                 ResultSet rs = st.executeQuery(sql);
                 Event event;

                 
                 while(rs.next()){
                     event = new Event(rs.getString("EventName"),rs.getString("Description"),rs.getString("ContactNumber"),rs.getString("EventTime"),rs.getString("Keyword"));
                     eventsList.add(event);
                 }
                 
                 
         } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        }
             return eventsList;
         }       
         public void show_event(){
             ArrayList<Event> list = eventList();
             DefaultTableModel model = (DefaultTableModel)jTable1_Display_Event.getModel();
             Object[] row = new Object[5];
             for(int i=0;i<list.size();i++){
                 row[0]=list.get(i).getEventName();
                 row[1]=list.get(i).getDescription();
                 row[2]=list.get(i).getContactNumber();
                 row[3]=list.get(i).getEventTime();
                 row[4]=list.get(i).getKeyword();
                 model.addRow(row);
                 
             }
             
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Des = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        Time = new javax.swing.JTextField();
        Key = new javax.swing.JTextField();
        NewButton1 = new javax.swing.JButton();
        DeleteButton2 = new javax.swing.JButton();
        DisplayButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_Event = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        SearchButton5 = new javax.swing.JButton();
        EditButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(84, 0, 205));
        jLabel1.setText("Event Handling");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(282, 282, 282))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(12, 12, 14));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Event Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Event Time");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Keyword");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        NewButton1.setBackground(new java.awt.Color(153, 255, 153));
        NewButton1.setText("New Entry");
        NewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButton1ActionPerformed(evt);
            }
        });

        DeleteButton2.setBackground(new java.awt.Color(255, 0, 0));
        DeleteButton2.setText("Delete Entry");
        DeleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton2ActionPerformed(evt);
            }
        });

        DisplayButton3.setBackground(new java.awt.Color(102, 255, 255));
        DisplayButton3.setText("Display Entry");
        DisplayButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButton3ActionPerformed(evt);
            }
        });

        jTable1_Display_Event.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1_Display_Event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EventName", "Description", "ContactNumber", "EventTime", "Keyword"
            }
        ));
        jTable1_Display_Event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_Display_EventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_Display_Event);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter Keyword to Search the Event");

        SearchButton5.setBackground(new java.awt.Color(51, 255, 255));
        SearchButton5.setText("Search Event");
        SearchButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton5ActionPerformed(evt);
            }
        });

        EditButton4.setBackground(new java.awt.Color(204, 0, 0));
        EditButton4.setText("Edit Event");
        EditButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(NewButton1)
                                .addGap(28, 28, 28)
                                .addComponent(DeleteButton2)
                                .addGap(28, 28, 28)
                                .addComponent(DisplayButton3))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Time, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                .addComponent(Contact, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Des, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Key)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addGap(45, 45, 45)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EditButton4)
                .addGap(195, 195, 195))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NewButton1)
                            .addComponent(DeleteButton2)
                            .addComponent(DisplayButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchButton5))
                    .addComponent(jLabel7))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void NewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButton1ActionPerformed
            
        try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","password");      
                 String query = "insert into handling(EventName, Description, ContactNumber, EventTime, Keyword)values(?,?,?,?,?)";
                 PreparedStatement pst = con.prepareStatement(query);
                 pst.setString(1,Name.getText());
                 pst.setString(2,Des.getText());
                 pst.setString(3,Contact.getText());
                 pst.setString(4,Time.getText());
                 pst.setString(5,Key.getText());
                 pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_Display_Event.getModel();
            model.setRowCount(0);
            show_event();
                         
                          
                         
                         
                         
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        }
                 
            
      Name.getText();
      Des.getText();
      Contact.getText();
      Time.getText();
      
      JOptionPane.showMessageDialog(null, "New Entry Added");
      
      

    }//GEN-LAST:event_NewButton1ActionPerformed

    private void DeleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton2ActionPerformed
     
        int reply =  JOptionPane.showConfirmDialog(
            null,
            "Delete the selected Event?",
            "Question",
            JOptionPane.YES_NO_OPTION);{

        if(reply ==JOptionPane.YES_OPTION ){
             try{
                 Class.forName("com.mysql.jdbc.Driver");
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sys","root","password");    
            int row = jTable1_Display_Event.getSelectedRow();
            String value=(jTable1_Display_Event.getModel().getValueAt(row,0).toString());           
            String query ="Delete from handling  where EventName="+value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)jTable1_Display_Event.getModel();
            model.setRowCount(0);
            show_event();
            
            JOptionPane.showMessageDialog(null,"Successfully Deleted.","Message",JOptionPane.ERROR_MESSAGE);
             }  
             catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);}
            
            
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Event is not deleted","Message",JOptionPane.WARNING_MESSAGE);
        } 
    }
    }//GEN-LAST:event_DeleteButton2ActionPerformed

    private void DisplayButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButton3ActionPerformed
        
        JOptionPane.showMessageDialog(null,"Entry Found");
    }//GEN-LAST:event_DisplayButton3ActionPerformed

    private void SearchButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton5ActionPerformed
       
        Search.getText();
        
        JOptionPane.showMessageDialog(null, "Event Found");
    }//GEN-LAST:event_SearchButton5ActionPerformed

    private void EditButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton4ActionPerformed
   
        JOptionPane.showConfirmDialog(null,"Edit the selected Event?","Question",JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_EditButton4ActionPerformed

    private void jTable1_Display_EventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_Display_EventMouseClicked
        int i =jTable1_Display_Event.getSelectedRow();
        TableModel model = jTable1_Display_Event.getModel();
        Name.setText(model.getValueAt(i,0).toString());
        Des.setText(model.getValueAt(i,1).toString());
        Contact.setText(model.getValueAt(i,2).toString());
        Time.setText(model.getValueAt(i,3).toString());
        Key.setText(model.getValueAt(i,4).toString());
        
    }//GEN-LAST:event_jTable1_Display_EventMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEvents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contact;
    private javax.swing.JButton DeleteButton2;
    private javax.swing.JTextField Des;
    private javax.swing.JButton DisplayButton3;
    private javax.swing.JButton EditButton4;
    private javax.swing.JTextField Key;
    private javax.swing.JTextField Name;
    private javax.swing.JButton NewButton1;
    private javax.swing.JTextField Search;
    private javax.swing.JButton SearchButton5;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_Event;
    // End of variables declaration//GEN-END:variables
}
